### PR TITLE
Update players.cfg ticket costs

### PR DESCRIPTION
**Pull request by sgtfuzzle17**
Adjusted ticket costs to balance campaign per below suggestion thread: https://discord.com/channels/894586277121388584/1202050044195242034/1202050044195242034

### CODE REVIEW

**Comment by ricmzn** [comment]
Most of these seem good changes given the current low thread level of the mission. However, I have a couple of reservations:

* Does the INS in the Mirage F1EE make a large enough difference to make it more valuable, or is this a a minor incentive like F-14A vs F-14B?
* The cost of the F-15E seems too high. I see it as being broadly the same weapons capability level of the F-14B (within the mission's weapon limitations), but with a better radar, more range, and systems that can be manned entirely from the front seat. Maybe we can make it just 2.0 points per aircraft?

**Comment by dharmab** [comment]
The F-15E is substantially more capable than the F-14B:

- In air to air, the radar is both objectively longer range (https://github.com/Quaggles/dcs-charts?tab=readme-ov-file) and subjectively much easier to operate (MFD page vs TID, can be operated from either seat)
- In air to ground, the F-15E's air to ground radar, better targeting pod, terrain following radar and NAVFLIR make it easier to execute both low level approaches and standoff attacks
- The workflow between the front and rear seats is easier to balance, since the crew can hand off task management to each other. The Tomcat is rigid in crew roles, with few overlapping responsibilities.

**Comment by sgtfuzzle17** [comment]
To chime in on this dialogue, these changes are not only directed at core module capability but also how they perform in the context of FPL. With what we've seen of campaigns getting knocked over in literally *hours*, there are issues with how things are balanced - I don't think I've seen a campaign even close to losing in a long time. Generally, costs need to be higher, and the Mudhen is the biggest example of that.

A big reason it's so far out in front is not just that you've got all the stuff the others have mentioned, but in the landscape of the Syria terrain that toolset becomes doubly effective, especially against the older LORAD/MERAD systems OPFOR has. The Strike Eagle is easily the most powerful asset, so making it have a bit more bite when one (or several) go down means people will need to at least be a bit more careful about how they operate. Idea of the whole ticket cost change is to make it such that a) supporting missions are more important and b) OPFOR stands half a chance at attriting BLUFOR. The thread on the LK Discord server generally supported this conclusion. I'd like to leave it as is.

**Comment by ricmzn** [comment]
Those are all good points. I'm merging this for a future update.

**Pull request merged**
